# -------- output path setting --------
hydra:
  run:
    dir: experiments/toy/${data_name}/${now:%Y-%m-%d_%H-%M-%S}


# -------- GPU & Data setting --------
gpu_id: 0
data_type: toy  # toy / mnist / cifar10 / custom (celebA gender)
train_type: generation # generation / translation

data_name: 8gaussians
# toy : 25gaussians / 8gaussians / swissroll / 2spirals / circles / 2sines / checkerboard / moon
p_data: ${data_name}
q_data: noise  # Set "noise" for Generation (Prior)


# -------- Train setting --------
mode: train # train / test
load: False
path: 
  f_path: 
  b_path: 

n_ipf: 10
num_steps: 8
gamma: {'min' : [0.01], 'max' : [0.05]}

sample_itr: 25
num_itr: 80
cache_num: 10  # for efficient training: replay-memory

alpha: 0.5
beta: 2.5

train_batch_size: 512
test_batch_size: 512

sb_lr: 1e-4
sb_lr_min: 1e-4
ema_decay: 0.9

# Logging
verbose_ipf: 2

# Use " export TORCH_CUDA_ARCH_LIST=8.0 " command for ninja error